# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a517145d0a1c859432f3fa4ebd700bb6b4648b9d1c82b3a9013087f4fdb19e03059e1c4e8c250c4d83d3b4a5f4ea6461758911c3b85a5a3415d1238bb88a7017

test:
  secret_key_base: fdb16344367066a00bcfb66d066a5054279fb080442c80e6821b226d1c2c92fa3d3300c50db6f4e3be97b21b9e53c6cb44df6c6badaccfab25c674e2148362ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
